# Generated by Django 4.2.5 on 2023-10-17 06:22

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, upload_to=myapp.models.Image.nameFile),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
